{% set name = "ipypublish" %}
{% set version = "0.10.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01c094d57bfee349b44f32922b9f843b36e137955f2a852507a5c04479af39e9

build:
  number: 2
  entry_points:
    - nbpublish = ipypublish.frontend.nbpublish:run
    - nbpresent = ipypublish.frontend.nbpresent:run
    - ipubpandoc = ipypublish.filters_pandoc.main:pandoc_filters
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - bibtexparser
    - docutils  # [py>27]
    - docutils <0.15  # [py<=27]
    - jinja2
    - jsonextended >=0.7
    - jsonschema
    - jupytext
    - nbconvert
    - nbformat
    - ordered-set
    - pandoc
    - panflute
    - pathlib2  # [py<34]
    - python
    - ruamel.yaml
    - ruamel.yaml.clib
    - setuptools
    - shutilwhich  # [py<33]
    - six
    - sphinx >=1.8
    - sphinxcontrib-bibtex
    - texsoup <0.2
    - tornado
    - traitlets
    - typing  # [py<35]

test:
  imports:
    - ipypublish
    - ipypublish.bib2glossary
    - ipypublish.convert
    - ipypublish.export_plugins
    - ipypublish.filters
    - ipypublish.filters_pandoc
    - ipypublish.filters_pandoc.tests
    - ipypublish.frontend
    - ipypublish.port_api
    - ipypublish.postprocessors
    - ipypublish.preprocessors
    - ipypublish.schema
    - ipypublish.scripts
    - ipypublish.sphinx
    - ipypublish.sphinx.gls
    - ipypublish.sphinx.notebook
    - ipypublish.sphinx.notebook.css
    - ipypublish.sphinx.tests
    - ipypublish.templates
    - ipypublish.templates.outline_schemas
    - ipypublish.templates.segments
    - ipypublish.tests
    - ipypublish.tests.test_files
  commands:
    - nbpublish --help
    - nbpresent --help
    - echo "a" | pandoc --filter ipubpandoc

about:
  home: https://github.com/chrisjsewell/ipypublish
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A workflow for creating and editing publication ready scientific reports, from one or more Jupyter Notebooks
  doc_url: https://ipypublish.readthedocs.io
  dev_url: https://github.com/chrisjsewell/ipypublish

extra:
  recipe-maintainers:
    - chrisjsewell
