travis:
  secure:
    BINSTAR_TOKEN: hLC2k/QCDrxQeqFWGZVIxRKGme5R5KTGTLD9pvho27mE+bF2YVcjRx7PWVu0CzLRjESRZkxFYagmzosB9fNrp+vlnRVHEBIqKdoFc/DbdkzlPAeIFTd5uliDyU4oDEiuYmqSOKRk3QglTqhwdgVIr6m5NxMSnnGz5rp7AXhwxS+gBmXDEsyRoyaeQ0rVh7Tszz28FTB/YIJzNtgJZUihv9mNmI6DjbaWgtGL9IMYdygtNStG71WAZ55BJo9qR9A2hcNtkxmxFWUSLOHtnUVZ8DmmHAw8S6qIT5g29cABFa33c/DB5tCvBBKbOOt1CdKohks6RYSa7vG6sp6RrPSBZy2bx2XwuBiV1nakNIJjpg6fsQlamxf4MUl+C+rELD69uIG1cXAZa3pk+lLN4j4eoCdpxeLuPoaFO63Q3SClQodFU/aLEd51AhvMJLziYCIVkvssX8PQba3aZyVsJ6Vq+Ko/oq/ax3wN7CHmA0q5PaYP9NH0hwezrgnt7UqDcWjgRBTCs7IpJZjH9ExLMBJtLN0Kgm46BBfHe371FDgz5y0UbvUhCSkFfx8PgyO9uXoTk1MlhRdJpvDcruXjYFjDCNyM84q5A0EMR0DgJ7JqNLOBaRd9TKhCU4Vsbxt3VVSlP/Ld6z78Px/sjojgAzoBxxtkYt+kwz9x+8tPY/T6XZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
